DELETE http://localhost:3001/api/logout
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBvdGF0b0Bwb3RhdG8uY29tIiwiaWQiOjEsImlhdCI6MTY2NzQwOTY2OX0.Yro1ZTh2hw72yAh0Bfkbfo3OXNRvE4eG_OYcz4HMsMo