POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBvdGF0byIsImlkIjoxLCJpYXQiOjE2NjczOTIyMzJ9.5ldh0FkkVs-F8kXBIEl2ASYFX_WgOz4XLmpOxLmHHtQ

{
	"author": "author name",
	"title": "title",
	"url": "url"
}