DELETE http://localhost:3001/api/blogs/1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBvdGF0b0Bwb3RhdG8uY29tIiwiaWQiOjEsImlhdCI6MTY2NzQwMTcxMn0.v8Aqsk25mGufzcz9jbJvgErbzjwUFDaezNr9rArtYGI